WITH FLATTENED_TABLE AS (
    SELECT 
        A.REPORT_DATE,
        A.SERVICE_ID,
        A.CUSTOMER_ID,
        A.CUSTOMER_SEGMENT_FLAG,
        A.CUSTOMER_GENDER,
        A.CUSTOMER_NATIONALITY,
        A.ORDER_TYPE,
        A.ORDER_TYPE_L2,
        A.SERVICE_NAME,
        A.SERVICE,
        B.SUBSCRIPTION_STATUS,
        CASE WHEN A.REPORT_DATE = (SELECT MIN(REPORT_DATE) FROM PROCESSED_ORDER_DAILY WHERE SERVICE_ID = A.SERVICE_ID 
        AND CUSTOMER_ID = A.CUSTOMER_ID) 
        THEN '1'
        ELSE '0'
        END AS IS_NEW_SIGNUP, -- The first order for a service = new signup
        CASE WHEN B.SUBSCRIPTION_STATUS = 'inactive' 
            AND (SELECT SUBSCRIPTION_STATUS FROM PROCESSED_ACTIVE_DAILY 
                WHERE SERVICE_ID = A.SERVICE_ID 
                AND CUSTOMER_ID = A.CUSTOMER_ID 
                AND REPORT_DATE < A.REPORT_DATE 
                ORDER BY REPORT_DATE DESC LIMIT 1) = 'active' 
            THEN '1'
            ELSE '0' 
        END AS IS_CHURN_EVENT, -- Service was previously active, but then marked as inactive subsequently
        CASE WHEN EXISTS (
                SELECT 1 
                FROM PROCESSED_ORDER_DAILY 
                WHERE SERVICE_ID = A.SERVICE_ID 
                AND CUSTOMER_ID != A.CUSTOMER_ID 
                AND REPORT_DATE < A.REPORT_DATE
            )
            THEN '1'
            ELSE '0' 
        END AS IS_TRANSFER -- Same service was assigned to different customer *before*
    FROM PROCESSED_ORDER_DAILY A
    JOIN PROCESSED_ACTIVE_DAILY B
    ON A.CUSTOMER_ID = B.CUSTOMER_ID 
    AND A.SERVICE_ID = B.SERVICE_ID
)

SELECT 
    REPORT_DATE,
    SERVICE_ID,
    CUSTOMER_ID,
    CUSTOMER_SEGMENT_FLAG,
    CUSTOMER_GENDER,
    CUSTOMER_NATIONALITY,
    ORDER_TYPE,
    ORDER_TYPE_L2,
    SERVICE_NAME,
    SERVICE,
    SUBSCRIPTION_STATUS,
    IS_NEW_SIGNUP,
    IS_CHURN_EVENT,
    IS_TRANSFER,
    EXTRACT(DAY FROM REPORT_DATE) AS DAY_NUMBER,
    EXTRACT(WEEK FROM REPORT_DATE) AS WEEK_NUMBER,
    EXTRACT(MONTH FROM REPORT_DATE) AS MONTH_NUMBER,
FROM FLATTENED_TABLE
ORDER BY REPORT_DATE, CUSTOMER_ID, SERVICE_ID
;
